version: 2

networks:
  primary:
    external:
      name: primary

services:
  web:
    image: registry.nush.app/library-app:latest
    restart: always
    networks:
    - primary
    expose:
    - "5000"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.library.rule=Host(`library.nush.app`)"
    - "traefik.http.routers.library.entrypoints=https"
    - "traefik.http.routers.library.tls=true"
    - "traefik.http.routers.library.tls.certresolver=tlsresolver"